
#pragma once

#include "NativeGameplayTags.h"

namespace RoGameplayTags
{
	// 输入Tag
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ctrl);

	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LMB);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_RMB);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Shift);


	// 技能Tag
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_NormalAttack_Start);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_NormalAttack_A);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_NormalAttack_B);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_NormalAttack_C);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_NormalAttack_D);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_NormalAttack_Attacking);
	
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_NormalAttack_Window);
	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_MoveCancel_Window);

	RO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Roll);
	

	
}
